# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       hawaii-eyesight

# >> macros
# << macros

Summary:    Hawaii desktop image viewer.
Version:    0.1.1.20130723.8d30485
Release:    1
Group:      Applications/System
License:    BSD
Source0:    eyesight-%{version}.tar.bz2
Source1:    eyesight.desktop
Source100:  hawaii-eyesight.yaml
BuildRequires:  pkgconfig(liblzma)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5PrintSupport)
BuildRequires:  cmake
BuildRequires:  bzip2-devel
#BuildRequires:  vibe-devel
BuildRequires:  qt5-qttools-linguist
BuildRequires:  desktop-file-utils

%description
Provides image viewer for Hawaii desktop


%prep
%setup -q -n eyesight

# >> setup
cp %{SOURCE1} data/eyesight.desktop
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/eyesight
%{_datadir}/applications/eyesight.desktop
%{_datadir}/eyesight/translations/
# >> files
# << files
